sudo: required
language: generic


services:
  - docker

before_install:
  - docker build -t subhamkp/docker-react -f Dockerfile.dev  .

script:
  - docker run -e CI=true subhamkp/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1" #As per the beanstalk url
  app: "react-docker-travis" #Beanstalk app name in AWS
  env: "react-docker" #Name of the env file created in beanstalk app
  bucket_name: "elasticbeanstalk-ap-south-1-277020176927" #Specify the name of the S3 bucket created automatically on creating beamstalk itself.
  bucket_path: "react-docker-travis" #It is mostly same as the app name  and folder created inside S3 bucket on first deployment
  on:
    branch: master #deploy only when pushed to git master branch 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY