#It is an alternate shorthand

version: "3"
services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev #specify docker file name with extension

        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules #nothing is mapped to node_modules present in container
            - .:/app #all files/dir of local are mapped to /app directory

    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev #specify docker file name with extension

        volumes: 
            - /app/node_modules #nothing is mapped to node_modules present in container
            - .:/app #all files/dir of local are mapped to /app directory

        command: ["npm","run","test"] #ovverride fefault command on start. Also, it reruns test command whenever above volume changes 